#!/bin/sh

git status

printf "\nSo you can commit, huh :)\nReminder to push to the remote repository 🌐.\n\n"

# automatically push to the remote
# git push origin $(git rev-parse --abbrev-ref HEAD)

# chmod +x .husky/*